process.env.DATABASE_URL ??= "postgresql://postgres:postgres@localhost:5432/worldcup2026_test?schema=public";
process.env.ADMIN_SYNC_TOKEN ??= "test-admin-sync-token-123";
process.env.ADMIN_SESSION_SECRET ??= "test-admin-session-secret-1234567890";
process.env.ADMIN_USERNAME ??= "admin";
process.env.THESPORTSDB_ENABLED ??= "false";
process.env.THESPORTSDB_KEY ??= "";
process.env.THESPORTSDB_BASE_URL ??= "https://www.thesportsdb.com/api/v1/json";
process.env.THESPORTSDB_LEAGUE_ID ??= "4429";
process.env.THESPORTSDB_SEASON ??= "2026";
